kind: pipeline
name: default

steps:
- name: build
  image: debian:8-slim
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - apt-get update -qqq && apt-get install -yqq --no-install-recommends make curl
    - curl -kfsSL https://get.docker.com | sh
    - make build push
