kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: pabsi/acestream-server
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    debug: true
