name: Run Dockerfile lint

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run dockerlint
    steps:
      - uses: actions/checkout@v2

      - name: Dockerfile lint
        uses: brpaz/hadolint-action@master
